version: '3.8'

services:
    php:
        build: .
        restart: unless-stopped
        working_dir: /app
        environment:
            DATABASE_URL: mysql://${MYSQL_USER:-app}:${MYSQL_PASSWORD:-123}@database:3306/${MYSQL_DATABASE:-app}?serverVersion=${MYSQL_VERSION:-8}&charset=${MYSQL_CHARSET:-utf8mb4}
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        command: php -S 0.0.0.0:8000 -t public
    
    database:
        image: mysql:${MYSQL_VERSION:-8}
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-123}
            MYSQL_USER: ${MYSQL_USER:-app}
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 5s
            retries: 5
            start_period: 60s
        volumes:
            - database_data:/var/lib/mysql:rw

volumes:
    database_data:
